defaults: &defaults
  :verbose: true
  :pidfile: ./tmp/sidekiq.pid
  :queues:
    - critical
    - default
    - low
  :concurrency: 1

development:
  <<: *defaults

production:
  <<: *defaults
  :logfile: ./log/sidekiq.log
  :concurrency: 25

:schedule:
  trigger_import_data:
    every: '5m'
    class: ImportAllDataJob
  trigger_crawl_events:
    cron: '0 8 1 * *'  # 毎月1日の8:00
    class: OfficialWebsite::CrawlEventsJob
  trigger_crawl_races:
    cron: '0 8 * * *'  # 毎日8:00
    class: OfficialWebsite::CrawlOpenedOrWillOpenRacesJob
